name: build and push dockerfiles

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, info, login, root]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.service }}.dockerfile
          push: true
          tags: |
            git.klsh.ru/khafizov/${{ matrix.service }}-web:latest
            git.klsh.ru/khafizov/${{ matrix.service }}-web:${{ github.ref_name }}

      - name: Job status
        run: echo "This job's status is ${{ job.status }}."
